server:
  port: 8080
  servlet:
    context-path: /DoctorCare
spring:
  application:
    name: NGUYENVIETBUU
  datasource:
    url: jdbc:mysql://localhost:3306/doctorcare888
    username: root
    password: 120101
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: nguyenvietbuu2001@gmail.com
    password: igtm wrtm obch rkig
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


jwt:
  signerKey: "2DU0iJ0m/Mug/wRqkvV78yjsbIPTss8pKA6ju5fNMfqt+jEAs9zzkLH6smWW0vmC"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  file:
    path: logs/local




